@startuml Class Diagram
title Product Model
class Product{
    -name
    -price
    -quantity
    --
    +getName()
    +getPrice()
    +getQuantity()
    --
    +setName(value)
    +setPrice(value)
    +setQuantity(value)
    --
    +Product(name, price, quantity)
}
@enduml