@startuml mathHelper
title static class
class MathHelper{
    +{static}add(a:int, b:int)
    +{static}substract(a:int, b:int)
    +{static}multipy(a:int, b:int)
    +{static}divide(a:int, b:int)
}
hide empty fields
@enduml