@startuml
title Car Model
class Car {
    -manufacturer:string
    -model:string
    -year:int
    +color:strin +openSunRoof():void
    +playRadio(station):void
    +drive():void
    +stop():void
}
@enduml