@startuml use-a
title use-a

class Engine {
  + start(): void
  + stop(): void
}

class Car {
  - engine: Engine
  + Car()
  + start(): void
  + stop(): void
}

Car  "uses" --> Engine

hide empty members
@enduml