@startuml is-a
title inheritance

class Animal {
    + name: String
    + makeSound(): String
}

class Dog {
    + makeSound(): String
}

class Cat {
    + makeSound(): String
}

Animal <|-down- Dog : <<extends>>
Animal <|-down- Cat :  <<extends>>


hide empty members
@enduml